### PR TITLE
Bump constraints for ghc 9.4.5 and bump resolver.

### PR DESCRIPTION
**Pull request by philderbeast**
Passes all 28 tests with both stack (`lts-20.18` so `ghc-9.2.7`) and cabal (with `ghc-9.4.5`) builds.

```
$ cabal test all --test-show-details=always
Build profile: -w ghc-9.4.5 -O1
In order, the following will be built (use -v for more details):
 - records-sop-0.1.1.0 (test:examples) (first run)
Preprocessing test suite 'examples' for records-sop-0.1.1.0..
Building test suite 'examples' for records-sop-0.1.1.0..
Running 1 test suites...
Test suite examples: RUNNING...

cast
  successfully casts X to X [✔]
  successfully casts A to A [✔]
  successfully casts A to X [✔]
  successfully casts B to B [✔]
  successfully casts B to X [✔]
  successfully casts B to A [✔]
  successfully casts B to C [✔]
  successfully casts C to X [✔]
  successfully casts C to A [✔]
  successfully casts C to B [✔]
  successfully casts E to E [✔]
  successfully casts E to X [✔]
  successfully casts E to A [✔]
  correctly fails to cast A to B [✔]
  correctly fails to cast A to C [✔]
  correctly fails to cast E to B [✔]
  correctly fails to cast E to C [✔]
  fails to cast F to anything (even X) [✔]
  fails to cast G to anything (even X) [✔]
  successfully extracts anInt from A [✔]
  successfully extracts aBool from A [✔]
  correctly fails to extract aChar from A [✔]
  successfully extracts anInt from B [✔]
  successfully extracts aBool from B [✔]
  successfully extracts aChar from B [✔]
  successfully extracts anInt from C [✔]
  successfully extracts aBool from C [✔]
  successfully extracts aChar from C [✔]

Finished in 0.0006 seconds
28 examples, 0 failures

Test suite examples: PASS
...
```

### CODE REVIEW

**Comment by philderbeast** [comment]
I also tested setting the stackage resolver to `nightly-2023-04-25` and this passed too.

**Comment by jship** [comment]
Perhaps it would be worthwhile to set `ghc-prim`'s upper bound to `< 0.11` instead of `< 0.10`? That would cover `ghc-prim` 0.10 for GHC 9.6. The [changelog](https://hackage.haskell.org/package/ghc-prim-0.10.0/changelog) entry for `ghc-prim`'s 0.10 release seems to indicate there should be no compatibility issues with `records-sop`.

**Comment by philderbeast** [comment]
Bumping `ghc-prim` we can build and pass tests with `ghc-9.6.2`.

I got a deprecation message. With `#if MIN_VERSION_base(4,12,0)` as the cutoff, I could do the suggested replacement.

```
$ cabal build all --enable-tests --enable-benchmarks
Resolving dependencies...
Build profile: -w ghc-9.6.2 -O1
...
src/Generics/SOP/Record.hs:8:14: warning: [-Wdeprecated-flags]
    -XTypeInType is deprecated: use -XDataKinds and -XPolyKinds instead
  |
8 | {-# LANGUAGE TypeInType #-}
  |              ^^^^^^^^^^

src/Generics/SOP/Record/SubTyping.hs:8:5: warning: [-Wdeprecated-flags]
    -XTypeInType is deprecated: use -XDataKinds and -XPolyKinds instead
  |
8 |   , TypeInType
  |     ^^^^^^^^^^
```

Here's why I had to keep `-XTypeInType` (got these error messages with the `-XDataKinds` and `-XPolyKinds` replacements).

```
$ cabal build all --enable-tests --enable-benchmarks
Resolving dependencies...
Build profile: -w ghc-8.4.1 -O1
...
src/Generics/SOP/Record.hs:147:70: error:
    • Type constructor ‘RecordCode’ cannot be used here
        (Perhaps you intended to use TypeInType)
    • In the kind ‘RecordCode’
    |
147 | type family ToRecordCode_Field (fis :: [FieldInfo]) (c :: [Type]) :: RecordCode where
    | 
 ...
 src/Generics/SOP/Record/SubTyping.hs:47:26: error:
    • Type constructor ‘RecordCode’ cannot be used here
        (Perhaps you intended to use TypeInType)
    • In the kind ‘RecordCode’
   |
47 | class IsSubTypeOf (r1 :: RecordCode) (r2 :: RecordCode) where
   |      
 ```

**Comment by kosmikus** [comment]
Thanks. Sorry for the long delay.

**Pull request merged**
