### PR TITLE
Export `get`

### PR DESCRIPTION
**Pull request by AriFordsham**
Why not?

### CODE REVIEW

**Comment by kosmikus** [comment]
Yes, you're right.

**Comment by AriFordsham** [comment]
What's the timeline for pushing to Hackage/Stackage? I need this for my work, and I'd rather not fiddle with building custom.

**Comment by kosmikus** [comment]
I can make a new release, but it's not terribly difficult to have a github dependency specified by git commit in both cabal and stack projects these days.

**Comment by AriFordsham** [comment]
Thanks! That should work. I'll look into doing that.

AF

**Comment by kosmikus** [comment]
Released as https://hackage.haskell.org/package/records-sop-0.1.1.0. I've added `getField` which I think is the function you actually want.

**Pull request merged**
